import React, { useMemo, useState } from 'react';
import { Bike, MapPin, Package, Search } from 'lucide-react';
import { Motoboy, Order, StoreShift } from '../types';
import { RouteMap } from './RouteMap';

type View = 'all' | 'orders' | 'motoboys';
type DriverFilter = 'all' | 'available' | 'delivering' | 'returning_to_store';

export const LiveDispatchMap: React.FC<{shift: StoreShift; orders: Order[]; motoboys: Motoboy[]}> = ({shift, orders, motoboys}) => {
  const [view,setView]=useState<View>('all'); const [driverFilter,setDriverFilter]=useState<DriverFilter>('all'); const [query,setQuery]=useState('');
  const liveOrders=useMemo(()=>orders.filter(o=>!['delivered','cancelled','failed'].includes(o.status)&&typeof o.lat==='number'&&o.lat!==0&&typeof o.lng==='number'&&o.lng!==0),[orders]);
  const liveDrivers=useMemo(()=>motoboys.filter(m=>m.status!=='offline'&&(driverFilter==='all'||m.status===driverFilter)),[motoboys,driverFilter]);
  const q=query.toLowerCase();
  const shownOrders=liveOrders.filter(o=>!q||`${o.displayCode||o.codeNumber} ${o.clientName} ${o.address}`.toLowerCase().includes(q));
  const shownDrivers=liveDrivers.filter(m=>!q||m.name.toLowerCase().includes(q));
  const badge=(s:string)=>s==='available'?'Disponível':s==='delivering'?'Em rota':s==='returning_to_store'?'Voltando':'Offline';
  const badgeClass=(s:string)=>s==='available'?'text-emerald-300 bg-emerald-500/15':s==='delivering'?'text-blue-300 bg-blue-500/15':s==='returning_to_store'?'text-amber-300 bg-amber-500/15':'text-slate-400 bg-slate-800';
  return <div className="space-y-3">
    <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-3"><div><h3 className="text-xl font-black text-white">Mapa de Despacho</h3><p className="text-xs text-slate-400">Pedidos e entregadores em tempo real.</p></div><div className="flex gap-2 flex-wrap">{([['all','Todos'],['orders','Pedidos'],['motoboys','Motoboys']] as const).map(([id,label])=><button key={id} onClick={()=>setView(id)} className={`px-4 py-2 rounded-lg border text-xs font-black ${view===id?'bg-violet-600 border-violet-500 text-white':'bg-slate-900 border-slate-800 text-slate-300'}`}>{id==='orders'?'📦':id==='motoboys'?'🛵':'◉'} {label}</button>)}</div></div>
    <div className="flex gap-2 flex-wrap">{view!=='orders'&&<>{([['all','Todos'],['available','Disponíveis'],['delivering','Em rota'],['returning_to_store','Voltando']] as const).map(([id,label])=><button key={id} onClick={()=>setDriverFilter(id)} className={`px-3 py-1.5 rounded-lg text-[11px] font-bold border ${driverFilter===id?'border-violet-500 text-violet-200 bg-violet-500/10':'border-slate-800 text-slate-400 bg-slate-900'}`}>{label} ({id==='all'?motoboys.filter(m=>m.status!=='offline').length:motoboys.filter(m=>m.status===id).length})</button>)}</>}</div>
    <div className="grid grid-cols-1 xl:grid-cols-12 gap-3">
      <div className="xl:col-span-9 h-[650px] rounded-xl overflow-hidden border border-slate-800 relative"><RouteMap origin={{name:shift.storeName||'Loja',address:shift.storeAddress||'',lat:shift.storeLat||-26.9194,lng:shift.storeLng||-49.0661}} motoboysList={view==='orders'?[]:shownDrivers} stops={view==='motoboys'?[]:shownOrders.map((o,i)=>({id:o.id,codeNumber:o.codeNumber,orderIndex:i+1,title:`${o.displayCode||'#'+o.codeNumber} - ${o.clientName}`,address:o.address,neighborhood:o.neighborhood,lat:o.lat,lng:o.lng,status:o.status==='in_transit'?'in_transit':'pending',priority:'medium',recipientName:o.clientName,phone:o.clientPhone,valueToReceive:o.total,motoboyId:o.assignedMotoboyId||undefined,motoboyName:o.assignedMotoboyName||undefined}))}/><div className="absolute left-3 bottom-3 z-[500] bg-slate-950/90 border border-slate-700 rounded-xl p-3 text-[10px] text-slate-300 backdrop-blur"><strong className="text-white block mb-2">Legenda</strong><div className="flex flex-wrap gap-3"><span>📍 Pedido</span><span className="text-emerald-300">● Disponível</span><span className="text-blue-300">● Em rota</span><span className="text-amber-300">● Voltando</span></div></div></div>
      <aside className="xl:col-span-3 bg-slate-900 border border-slate-800 rounded-xl p-3 min-h-[650px]"><div className="relative mb-3"><Search className="absolute left-3 top-2.5 w-4 h-4 text-slate-500"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar pedido ou motoboy..." className="w-full bg-slate-950 border border-slate-800 rounded-lg pl-9 pr-3 py-2 text-xs outline-none focus:border-violet-500"/></div>{view!=='motoboys'&&<div className="mb-4"><h4 className="text-xs font-black mb-2 flex items-center gap-1.5"><Package className="w-3.5 h-3.5 text-violet-400"/>Pedidos no mapa ({shownOrders.length})</h4><div className="space-y-2 max-h-[300px] overflow-y-auto">{shownOrders.map(o=><div key={o.id} className="bg-slate-950/60 border border-slate-800 rounded-lg p-2.5"><div className="flex justify-between"><strong className="text-xs">{o.displayCode||`#${o.codeNumber}`}</strong><span className="text-[10px] text-slate-500">{o.status==='in_transit'?'Em rota':'Aguardando'}</span></div><p className="text-[11px] text-slate-300 mt-1">{o.clientName}</p><p className="text-[10px] text-slate-500 mt-1 flex gap-1"><MapPin className="w-3 h-3 shrink-0"/>{o.address}</p></div>)}</div></div>}{view!=='orders'&&<div><h4 className="text-xs font-black mb-2 flex items-center gap-1.5"><Bike className="w-3.5 h-3.5 text-emerald-400"/>Entregadores ({shownDrivers.length})</h4><div className="space-y-2">{shownDrivers.map(m=><div key={m.id} className="bg-slate-950/60 border border-slate-800 rounded-lg p-2.5 flex items-center justify-between"><div><strong className="text-xs">{m.name}</strong><p className={`inline-block ml-2 px-1.5 py-0.5 rounded text-[9px] font-bold ${badgeClass(m.status)}`}>{badge(m.status)}</p></div><span className="text-[10px] text-slate-500">{orders.filter(o=>o.assignedMotoboyId===m.id&&!['delivered','cancelled','failed'].includes(o.status)).length} entregas</span></div>)}</div></div>}</aside>
    </div>
  </div>;
};
