import React, { useEffect, useMemo, useState } from 'react';
import { Motoboy, Order } from '../types';
import { CheckCircle2, Printer, X, Clock3, WalletCards } from 'lucide-react';
import { isCashPayment, PaymentBadge } from '../utils/paymentUtils';

interface Props { isOpen:boolean; onClose:()=>void; motoboys:Motoboy[]; orders:Order[]; }
const dateKey=(d=new Date())=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const orderDay=(o:Order)=>o.deliveredDate||o.createdDate||(()=>{const d=o.deliveredTimestamp?new Date(o.deliveredTimestamp):new Date(o.deliveredAt||o.createdAt);return Number.isNaN(d.getTime())?'':dateKey(d)})();
const norm=(v?:string|null)=>(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
const belongs=(o:Order,m:Motoboy)=>{const id=norm(o.assignedMotoboyId),name=norm(o.assignedMotoboyName),mid=norm(m.id),mn=norm(m.name),user=norm(m.username);return !!((mid&&id===mid)||(mn&&name===mn)||(user&&id===user)||(mn&&id===mn)||(mn&&name.includes(mn)));};
const settlementKey=(day:string,id:string)=>`rota_facil_settlement_${day}_${id}`;

export const MotoboySettlementModal:React.FC<Props>=({isOpen,onClose,motoboys,orders})=>{
 const today=dateKey();
 const [selected,setSelected]=useState(motoboys[0]?.id||'');
 const [version,setVersion]=useState(0);
 useEffect(()=>{if(isOpen&&!selected&&motoboys[0])setSelected(motoboys[0].id)},[isOpen,motoboys,selected]);
 const todayDelivered=useMemo(()=>orders.filter(o=>o.status==='delivered'&&orderDay(o)===today),[orders,today]);
 const rows=motoboys.map(m=>{const list=todayDelivered.filter(o=>belongs(o,m));const fixed=m.fixedFee||40;const per=m.perDeliveryFee||6.5;const earnings=fixed+list.length*per;const cash=list.filter(o=>isCashPayment(o.paymentMethod)).reduce((s,o)=>s+(o.total||0),0);const settled=localStorage.getItem(settlementKey(today,m.id))==='1';return {m,list,fixed,per,earnings,cash,net:cash-earnings,settled};});
 const current=rows.find(r=>r.m.id===selected)||rows[0];
 const paid=rows.filter(r=>r.settled).length, open=rows.filter(r=>!r.settled&&r.list.length>0).length, noMovement=rows.filter(r=>r.list.length===0).length;
 if(!isOpen)return null;
 const mark=()=>{if(!current)return;localStorage.setItem(settlementKey(today,current.m.id),'1');setVersion(v=>v+1)};
 const reopen=()=>{if(!current)return;localStorage.removeItem(settlementKey(today,current.m.id));setVersion(v=>v+1)};
 const print=()=>{if(!current)return;const w=window.open('','_blank','width=480,height=720');if(!w)return;w.document.write(`<html><body style="font-family:Arial;padding:24px"><h2>Acerto de Motoboy</h2><p>${new Date().toLocaleDateString('pt-BR')}</p><hr><b>${current.m.name}</b><p>Entregas: ${current.list.length}</p><p>Diária: R$ ${current.fixed.toFixed(2)}</p><p>Corridas: R$ ${(current.list.length*current.per).toFixed(2)}</p><p><b>Total a receber: R$ ${current.earnings.toFixed(2)}</b></p><p>Dinheiro recebido de clientes: R$ ${current.cash.toFixed(2)}</p><hr><h3>${current.net>=0?'Motoboy entrega à loja':'Loja paga ao motoboy'}: R$ ${Math.abs(current.net).toFixed(2)}</h3><p>Status: ${current.settled?'QUITADO':'EM ABERTO'}</p></body></html>`);w.document.close();setTimeout(()=>w.print(),200)};
 return <div className="fixed inset-0 z-50 bg-slate-950/80 backdrop-blur-sm flex items-center justify-center p-4">
  <div className="bg-slate-900 text-slate-100 rounded-2xl max-w-5xl w-full border border-slate-700 overflow-hidden flex flex-col max-h-[94vh]">
   <div className="p-5 bg-slate-950 border-b border-slate-800 flex justify-between items-center"><div><h3 className="font-extrabold text-white text-lg">Acerto dos Motoboys</h3><p className="text-xs text-slate-400">Movimento de hoje • {new Date().toLocaleDateString('pt-BR')}</p></div><button onClick={onClose}><X className="w-5 h-5"/></button></div>
   <div className="p-5 overflow-y-auto space-y-5">
    <div className="grid grid-cols-3 gap-3"><div className="p-3 rounded-xl bg-amber-500/10 border border-amber-500/30"><span className="text-xs text-amber-300">Em aberto</span><b className="block text-2xl">{open}</b></div><div className="p-3 rounded-xl bg-emerald-500/10 border border-emerald-500/30"><span className="text-xs text-emerald-300">Quitados</span><b className="block text-2xl">{paid}</b></div><div className="p-3 rounded-xl bg-slate-950 border border-slate-800"><span className="text-xs text-slate-400">Sem movimento</span><b className="block text-2xl">{noMovement}</b></div></div>
    <div className="grid md:grid-cols-[320px_1fr] gap-4">
     <div className="space-y-2"><h4 className="text-xs font-bold text-slate-400 uppercase">Entregadores</h4>{rows.map(r=><button key={r.m.id} onClick={()=>setSelected(r.m.id)} className={`w-full p-3 rounded-xl border text-left ${current?.m.id===r.m.id?'border-blue-500 bg-blue-500/10':'border-slate-800 bg-slate-950'}`}><div className="flex justify-between"><b>{r.m.name}</b><span className={`text-[10px] px-2 py-0.5 rounded-full ${r.settled?'bg-emerald-500/20 text-emerald-300':r.list.length?'bg-amber-500/20 text-amber-300':'bg-slate-800 text-slate-400'}`}>{r.settled?'QUITADO':r.list.length?'EM ABERTO':'SEM MOVIMENTO'}</span></div><span className="text-xs text-slate-400">{r.list.length} entregas • R$ {r.earnings.toFixed(2)} a receber</span></button>)}</div>
     {current&&<div className="space-y-4"><div className="flex justify-between items-start"><div><h4 className="text-xl font-bold">{current.m.name}</h4><p className="text-xs text-slate-400">Fechamento individual do dia</p></div><span className={`px-3 py-1 rounded-full text-xs font-bold ${current.settled?'bg-emerald-500 text-slate-950':'bg-amber-500/20 text-amber-300'}`}>{current.settled?'QUITADO':'EM ABERTO'}</span></div>
      <div className="grid sm:grid-cols-4 gap-2"><div className="p-3 bg-slate-950 border border-slate-800 rounded-xl"><span className="text-xs text-slate-400">Entregas</span><b className="block text-xl">{current.list.length}</b></div><div className="p-3 bg-slate-950 border border-slate-800 rounded-xl"><span className="text-xs text-slate-400">Diária + corridas</span><b className="block text-xl text-emerald-400">R$ {current.earnings.toFixed(2)}</b></div><div className="p-3 bg-slate-950 border border-slate-800 rounded-xl"><span className="text-xs text-slate-400">Dinheiro em mãos</span><b className="block text-xl text-amber-300">R$ {current.cash.toFixed(2)}</b></div><div className="p-3 bg-slate-950 border border-slate-800 rounded-xl"><span className="text-xs text-slate-400">Acerto</span><b className="block text-xl">R$ {Math.abs(current.net).toFixed(2)}</b><small className="text-slate-500">{current.net>=0?'entrega à loja':'loja paga'}</small></div></div>
      <div className="p-4 bg-slate-950 border border-slate-800 rounded-xl"><div className="flex justify-between text-xs"><span>Diária fixa</span><b>R$ {current.fixed.toFixed(2)}</b></div><div className="flex justify-between text-xs mt-2"><span>Corridas ({current.list.length} × R$ {current.per.toFixed(2)})</span><b>R$ {(current.list.length*current.per).toFixed(2)}</b></div><div className="flex justify-between text-sm mt-3 pt-3 border-t border-slate-800"><b>Total do motoboy</b><b className="text-emerald-400">R$ {current.earnings.toFixed(2)}</b></div></div>
      <div className="border border-slate-800 rounded-xl overflow-hidden"><div className="px-3 py-2 bg-slate-950 text-xs font-bold">Entregas de hoje</div><div className="max-h-52 overflow-y-auto">{current.list.length?current.list.map(o=><div key={o.id} className="px-3 py-2 border-t border-slate-800 flex justify-between"><div><b className="text-xs">#{o.codeNumber} • {o.clientName}</b><p className="text-[11px] text-slate-500">{o.address}</p></div><div className="text-right"><b className="text-xs">R$ {(o.total||0).toFixed(2)}</b><PaymentBadge method={o.paymentMethod} changeFor={o.changeFor} total={o.total} size="xs"/></div></div>):<div className="p-5 text-center text-slate-500 text-xs">Nenhuma entrega concluída hoje.</div>}</div></div>
     </div>}
    </div>
   </div>
   {current&&<div className="p-4 bg-slate-950 border-t border-slate-800 flex gap-2 justify-end"><button onClick={print} className="px-4 py-2 bg-slate-800 rounded-xl text-xs font-bold flex gap-2"><Printer className="w-4 h-4"/>Imprimir</button>{current.settled?<button onClick={reopen} className="px-4 py-2 bg-slate-800 border border-slate-700 rounded-xl text-xs font-bold"><Clock3 className="w-4 h-4 inline mr-1"/>Reabrir acerto</button>:<button disabled={!current.list.length} onClick={mark} className="px-5 py-2 bg-emerald-600 disabled:opacity-40 rounded-xl text-xs font-extrabold flex gap-2"><CheckCircle2 className="w-4 h-4"/>Marcar como quitado</button>}</div>}
  </div>
 </div>;
};
