import React, { useMemo, useState } from 'react';
import { Bike, CheckCircle2, Clock3, MapPin, Navigation, PackageOpen, Search, X } from 'lucide-react';
import { Motoboy, Order, Stop, StoreShift } from '../types';
import ReactiveRouteMap from './ReactiveRouteMap';

interface P {orders:Order[];motoboys:Motoboy[];shift:StoreShift;activeOrders:Order[];unassignedOrders:Order[];motoboysAvailable:Motoboy[];selectedOrderIds:string[];setSelectedOrderIds:(ids:string[])=>void;selectedMotoboyId:string|null;setSelectedMotoboyId:(id:string|null)=>void;onAssignOrderToMotoboy:(orderId:string,motoboyId:string)=>void;onAssignBatchToMotoboy?:(orderIds:string[],motoboyId:string)=>void;onUpdateOrderStatus:(orderId:string,status:Order['status'])=>void;onUpdateMotoboyStatus?:(motoboyId:string,status:Motoboy['status'])=>void;onOpenNewOrderModal:()=>void;onOpenMotoboyModal:()=>void;onSelectOrderForTracking:(order:Order)=>void;setIsRouteModalOpen:(open:boolean)=>void;setTicketOrder:(order:Order)=>void;setIsTicketOpen:(open:boolean)=>void;handleCallCounter:(motoboyId:string,motoboyName:string)=>void;triggerActionToast:(msg:string)=>void;setActiveTab:(tab:any)=>void;getMotoboyLoad:(motoboyId:string)=>number;assignOrderRespectingLoad:(orderId:string,motoboyId:string)=>void}
type Stage='waiting'|'preparing'|'ready'|'route';type MapMode='all'|'orders'|'drivers';type MapOrderFilter='all'|Stage;type MapDriverFilter='all'|'available'|'delivering'|'returning_to_store';
const money=(value=0)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(value)||0);
const code=(o:Order)=>o.displayCode||`#${o.codeNumber}`;
const isRoute=(o:Order)=>['picked_up','in_transit','dispatched'].includes(o.status);
const stage=(o:Order):Stage=>isRoute(o)?'route':o.status==='ready_at_counter'?'ready':o.assignedMotoboyId?'preparing':'waiting';
const stamp=(o:Order)=>Number(o.createdTimestamp)||Date.now();
const minsSince=(value?:number)=>Math.max(0,Math.floor((Date.now()-(Number(value)||Date.now()))/60000));
const readyStamp=(o:Order)=>Number((o as any).readyAt||(o as any).readyTimestamp||(o as any).statusUpdatedAt)||stamp(o);
const driverLabel=(m?:Motoboy)=>!m?'Sem entregador':m.status==='available'?'Disponível':m.status==='delivering'?'Em entrega':m.status==='returning_to_store'?'Voltando':m.status==='offline'?'Offline':'Ocupado';
const distanceKm=(a?:number,b?:number,c?:number,d?:number)=>{if(![a,b,c,d].every(v=>typeof v==='number'&&Number.isFinite(v)))return null;const r=(n:number)=>n*Math.PI/180,R=6371,x=r(c!-a!),y=r(d!-b!),q=Math.sin(x/2)**2+Math.cos(r(a!))*Math.cos(r(c!))*Math.sin(y/2)**2;return R*2*Math.atan2(Math.sqrt(q),Math.sqrt(1-q))};
const returnEta=(m:Motoboy,s:StoreShift)=>{if(m.status==='available')return'na loja / disponível';if(m.status==='delivering')return'após finalizar a rota';if(m.status!=='returning_to_store')return'sem previsão';const km=distanceKm(m.currentLat,m.currentLng,s.storeLat,s.storeLng);return km==null?'~5–10 min':`~${Math.max(2,Math.round(km/25*60))} min`};

export const OperationDispatchView:React.FC<P>=(p)=>{
 const{motoboys,shift,activeOrders,motoboysAvailable,onSelectOrderForTracking,onUpdateOrderStatus,assignOrderRespectingLoad,handleCallCounter,triggerActionToast}=p;
 const[q,setQ]=useState(''),[selected,setSelected]=useState<string[]>([]),[batchDriver,setBatchDriver]=useState(''),[manage,setManage]=useState(false),[mapMode,setMapMode]=useState<MapMode>('all'),[mapOrderFilter,setMapOrderFilter]=useState<MapOrderFilter>('all'),[mapDriverFilter,setMapDriverFilter]=useState<MapDriverFilter>('all'),[focusDriverId,setFocusDriverId]=useState<string|null>(null);
 const filtered=useMemo(()=>activeOrders.filter(o=>!q||`${code(o)} ${o.clientName} ${o.address} ${o.neighborhood||''}`.toLowerCase().includes(q.toLowerCase())),[activeOrders,q]);
 const g=useMemo(()=>({waiting:filtered.filter(o=>stage(o)==='waiting').sort((a,b)=>stamp(a)-stamp(b)),preparing:filtered.filter(o=>stage(o)==='preparing'),ready:filtered.filter(o=>stage(o)==='ready').sort((a,b)=>readyStamp(a)-readyStamp(b)),route:filtered.filter(o=>stage(o)==='route')}),[filtered]);
 const critical=useMemo(()=>[...g.ready.filter(o=>minsSince(readyStamp(o))>=10),...g.waiting.filter(o=>minsSince(stamp(o))>=15)],[g.ready,g.waiting]);
 const mapOrders=useMemo(()=>activeOrders.filter(o=>!['delivered','cancelled'].includes(o.status)&&typeof o.lat==='number'&&typeof o.lng==='number'&&(!focusDriverId||o.assignedMotoboyId===focusDriverId)&&(mapOrderFilter==='all'||stage(o)===mapOrderFilter)),[activeOrders,focusDriverId,mapOrderFilter]);
 const mapDrivers=useMemo(()=>motoboys.filter(m=>m.status!=='offline'&&(!focusDriverId||m.id===focusDriverId)&&(mapDriverFilter==='all'||m.status===mapDriverFilter)),[motoboys,focusDriverId,mapDriverFilter]);
 const stops:Stop[]=useMemo(()=>mapOrders.map((o,i)=>({id:o.id,codeNumber:o.codeNumber,orderIndex:i+1,title:`${code(o)} - ${o.clientName}`,recipientName:o.clientName,address:o.address,neighborhood:o.neighborhood,lat:o.lat,lng:o.lng,status:isRoute(o)?'in_transit':'pending',priority:'medium',motoboyId:o.assignedMotoboyId||undefined,motoboyName:o.assignedMotoboyName||undefined}as Stop)),[mapOrders]);
 const toggle=(id:string)=>setSelected(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id]);
 const batch=()=>{if(!batchDriver||!selected.length)return;selected.forEach(id=>assignOrderRespectingLoad(id,batchDriver));triggerActionToast(`${selected.length} pedido(s) vinculados ao entregador.`);setSelected([]);setBatchDriver('')};
 const assignCritical=(o:Order)=>{const next=motoboysAvailable[0];if(!next){triggerActionToast('Nenhum entregador disponível na fila agora.');return}assignOrderRespectingLoad(o.id,next.id);triggerActionToast(`${code(o)} atribuído a ${next.name}, próximo da fila.`)};
 const cols:[Stage,string,string,Order[]][]=[['waiting','Aguardando entregador','Pedidos ainda sem entregador',g.waiting],['preparing','Entregador atribuído','Carga reservada para retirada',g.preparing],['ready','Pronto para retirada','Prioridade da expedição',g.ready],['route','Em entrega','Pedidos na rua agora',g.route]];
 const empty:{[K in Stage]:string}={waiting:'Nenhum pedido aguardando entregador',preparing:'Nenhuma carga atribuída',ready:'Nenhum pedido pronto para retirada',route:'Nenhum pedido em entrega'};
 const Card=({o,s}:{o:Order;s:Stage})=>{const m=motoboys.find(x=>x.id===o.assignedMotoboyId),wait=s==='ready'?minsSince(readyStamp(o)):minsSince(stamp(o)),late=(s==='ready'&&wait>=10)||(s==='waiting'&&wait>=15);return <article onClick={()=>s==='waiting'&&toggle(o.id)} className={`rounded-lg border p-3.5 bg-[#10141c] transition ${s==='waiting'?'cursor-pointer hover:border-slate-600':''} ${selected.includes(o.id)?'border-violet-500':'border-slate-800'} ${late?'ring-1 ring-red-500/30':''}`}>
  {s==='waiting'&&<div className={`float-right w-4 h-4 rounded border grid place-items-center ${selected.includes(o.id)?'bg-violet-600 border-violet-500':'border-slate-600'}`}>{selected.includes(o.id)&&<CheckCircle2 className="w-3 h-3 text-white"/>}</div>}
  <div className="flex justify-between gap-3"><div><b className="text-base text-white">{code(o)}</b><p className="text-sm text-slate-200 mt-1">{o.clientName}</p></div><b className="text-sm text-white whitespace-nowrap">{money(o.total)}</b></div>
  <p className="text-xs text-slate-400 mt-2 flex gap-1.5"><MapPin className="w-3.5 h-3.5 shrink-0"/>{o.address}</p>
  {s==='waiting'&&<p className={`text-xs mt-2 ${late?'text-red-300':'text-slate-400'}`}><Clock3 className="w-3.5 h-3.5 inline mr-1"/>Aguardando entregador há {wait} min</p>}
  {s==='preparing'&&<><p className="text-xs text-slate-300 mt-2"><Bike className="w-3.5 h-3.5 inline mr-1"/>{o.assignedMotoboyName} · {driverLabel(m)}</p><button onClick={e=>{e.stopPropagation();onUpdateOrderStatus(o.id,'ready_at_counter')}} className="w-full mt-3 h-9 border border-slate-700 hover:border-violet-500 bg-slate-900 text-white rounded-md text-xs font-semibold">Marcar como pronto</button></>}
  {s==='ready'&&<><div className={`mt-2 text-xs font-semibold ${late?'text-red-300':'text-slate-300'}`}>{late?'Atraso · ':''}Aguardando retirada há {wait} min</div><p className="text-xs text-slate-300 mt-1"><Bike className="w-3.5 h-3.5 inline mr-1"/>{o.assignedMotoboyName||'Sem entregador'} · {driverLabel(m)}</p>{!o.assignedMotoboyId&&<button onClick={e=>{e.stopPropagation();assignCritical(o)}} className="w-full mt-3 h-9 bg-violet-600 hover:bg-violet-500 text-white rounded-md text-xs font-semibold">Atribuir próximo entregador</button>}</>}
  {s==='route'&&<div className="mt-3 flex justify-between items-center"><span className="text-xs text-slate-300">{o.assignedMotoboyName||'Em rota'}</span><button onClick={e=>{e.stopPropagation();onSelectOrderForTracking(o)}} className="text-xs font-semibold text-violet-300">Rastrear</button></div>}
 </article>};
 const chip=(active:boolean,disabled=false)=>`h-9 px-3 rounded-lg border text-xs font-medium whitespace-nowrap ${disabled?'opacity-35 cursor-not-allowed bg-slate-950 border-slate-800 text-slate-500':active?'bg-violet-600 border-violet-500 text-white':'bg-slate-950 border-slate-700 text-slate-300 hover:border-slate-500'}`;
 const orderFilterCount=(id:MapOrderFilter)=>id==='all'?activeOrders.length:activeOrders.filter(o=>stage(o)===id).length;
 const driverFilterCount=(id:MapDriverFilter)=>id==='all'?motoboys.filter(m=>m.status!=='offline').length:motoboys.filter(m=>m.status===id).length;
 const queueIndex=(m:Motoboy)=>motoboysAvailable.findIndex(x=>x.id===m.id);
 const sortedDrivers=useMemo(()=>[...motoboys].filter(m=>m.status!=='offline').sort((a,b)=>{const ai=queueIndex(a),bi=queueIndex(b);if(ai>=0&&bi>=0)return ai-bi;if(ai>=0)return-1;if(bi>=0)return 1;return a.name.localeCompare(b.name)}),[motoboys,motoboysAvailable]);
 return <div className="space-y-4">
  <header className="flex flex-col lg:flex-row lg:items-center justify-between gap-3"><h2 className="text-xl font-semibold text-white">Pedidos</h2><div className="flex gap-2"><div className="relative"><Search className="w-4 h-4 absolute left-3 top-2.5 text-slate-500"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar pedido, cliente ou endereço" className="w-[290px] max-w-[55vw] bg-slate-950 border border-slate-700 rounded-lg pl-9 pr-3 h-9 text-xs text-white"/></div><button onClick={()=>setManage(true)} className="h-9 px-4 bg-violet-600 hover:bg-violet-500 text-white rounded-lg text-xs font-semibold flex items-center gap-2"><Navigation className="w-3.5 h-3.5"/>Gestão de entrega</button></div></header>
  <div className="flex flex-wrap items-center gap-x-5 gap-y-2 text-sm text-slate-300 border-y border-slate-800 py-3"><span><b className="text-white">{activeOrders.length}</b> ativos</span><span><b className="text-white">{g.preparing.length}</b> atribuídos</span><span><b className="text-white">{g.ready.length}</b> prontos</span><span><b className="text-white">{g.route.length}</b> em entrega</span><span><b className="text-white">{motoboysAvailable.length}</b> {motoboysAvailable.length===1?'entregador disponível':'entregadores disponíveis'}</span></div>
  {critical.slice(0,3).map(o=>{const s=stage(o),wait=s==='ready'?minsSince(readyStamp(o)):minsSince(stamp(o));return <div key={o.id} className="flex flex-wrap items-center gap-3 rounded-lg border border-red-500/35 bg-red-950/20 px-4 py-3"><div className="flex-1 min-w-[260px]"><b className="text-sm text-red-200">{code(o)} {s==='ready'?'aguardando retirada':'sem entregador'} há {wait} min</b><p className="text-xs text-slate-400 mt-0.5">{o.clientName} · {o.neighborhood||o.address}</p></div>{!o.assignedMotoboyId&&<button onClick={()=>assignCritical(o)} className="h-8 px-3 rounded-md bg-violet-600 text-white text-xs font-semibold">Atribuir entregador</button>}<button onClick={()=>onSelectOrderForTracking(o)} className="h-8 px-3 rounded-md border border-slate-700 text-slate-200 text-xs">Ver pedido</button></div>})}
  {selected.length>0&&<div className="bg-[#151126] border border-violet-500/40 rounded-lg px-3 py-2.5 flex items-center gap-2"><b className="text-xs text-white">{selected.length} selecionado(s)</b><select value={batchDriver} onChange={e=>setBatchDriver(e.target.value)} className="ml-auto h-8 min-w-[190px] bg-slate-950 border border-slate-700 text-slate-200 rounded-md px-2 text-xs"><option value="">Escolher entregador...</option>{motoboys.filter(m=>m.status!=='offline').map(m=><option key={m.id} value={m.id}>{m.name} — {driverLabel(m)}</option>)}</select><button disabled={!batchDriver} onClick={batch} className="h-8 bg-violet-600 disabled:opacity-40 text-white rounded-md px-3 text-xs">Vincular</button><button onClick={()=>setSelected([])} className="w-8 h-8"><X className="w-4 h-4"/></button></div>}
  <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-3">{cols.map(([id,title,sub,items])=><section key={id} className="min-w-0"><div className="pb-3 border-b border-slate-800"><h3 className="text-sm font-semibold text-white">{title} · {items.length}</h3><p className="text-xs text-slate-500 mt-1">{sub}</p></div><div className="pt-3 space-y-2 min-h-[220px] max-h-[610px] overflow-y-auto">{items.length?items.map(o=><Card key={o.id} o={o} s={id}/>):<div className="h-40 grid place-items-center text-center px-4"><div><PackageOpen className="w-7 h-7 text-slate-600 mx-auto mb-2"/><p className="text-xs text-slate-500">{empty[id]}</p></div></div>}</div></section>)}</div>
  {manage&&<div className="fixed inset-0 z-[80] bg-black/80 p-4 flex items-center justify-center"><div className="w-full max-w-[1500px] h-[88vh] bg-[#0b0d12] border border-slate-800 rounded-2xl overflow-hidden flex flex-col"><div className="px-5 py-3 border-b border-slate-800 flex justify-between"><div><h3 className="text-white text-base font-semibold">Gestão de entrega</h3><p className="text-xs text-slate-400 mt-1">Acompanhe pedidos, entregadores e a ordem da fila.</p></div><button onClick={()=>setManage(false)}><X className="w-5 h-5 text-slate-400"/></button></div>
   <div className="px-5 py-3 border-b border-slate-800 flex flex-wrap gap-5 items-end"><div><p className="text-xs text-slate-400 mb-2">Mostrar no mapa</p><div className="flex gap-2">{([['all','Pedidos + entregadores'],['orders','Só pedidos'],['drivers','Só entregadores']]as[MapMode,string][]).map(([id,l])=><button key={id} onClick={()=>setMapMode(id)} className={chip(mapMode===id)}>{l}</button>)}</div></div>{mapMode!=='drivers'&&<div><p className="text-xs text-slate-400 mb-2">Filtrar pedidos</p><div className="flex gap-2 flex-wrap">{([['all','Todos'],['waiting','Sem entregador'],['preparing','Atribuídos'],['ready','Prontos'],['route','Em entrega']]as[MapOrderFilter,string][]).map(([id,l])=>{const n=orderFilterCount(id),disabled=n===0&&id!=='all';return <button key={id} disabled={disabled} onClick={()=>!disabled&&setMapOrderFilter(id)} className={chip(mapOrderFilter===id,disabled)}>{l} ({n})</button>})}</div></div>}{mapMode!=='orders'&&<div><p className="text-xs text-slate-400 mb-2">Filtrar entregadores</p><div className="flex gap-2 flex-wrap">{([['all','Todos'],['available','Disponíveis'],['delivering','Em entrega'],['returning_to_store','Voltando']]as[MapDriverFilter,string][]).map(([id,l])=>{const n=driverFilterCount(id),disabled=n===0&&id!=='all';return <button key={id} disabled={disabled} onClick={()=>!disabled&&setMapDriverFilter(id)} className={chip(mapDriverFilter===id,disabled)}>{l} ({n})</button>})}</div></div>}</div>
   <div className="grid lg:grid-cols-[minmax(0,1fr)_350px] flex-1 min-h-0"><div className="p-3 min-h-0"><ReactiveRouteMap origin={{name:shift.storeName||'Loja',address:shift.storeAddress||'',lat:shift.storeLat||-26.9194,lng:shift.storeLng||-49.0661}} stops={mapMode==='drivers'?[]:stops} motoboysList={mapMode==='orders'?[]:mapDrivers} selectedMotoboyId={focusDriverId} onSelectMotoboy={(id:string|null)=>setFocusDriverId(id)}/></div><aside className="border-l border-slate-800 p-3 overflow-y-auto"><h4 className="text-sm font-semibold text-white mb-1">Fila de entregadores</h4><p className="text-xs text-slate-500 mb-3">O primeiro disponível é o próximo a receber uma saída.</p>{sortedDrivers.map(m=>{const qi=queueIndex(m),focused=focusDriverId===m.id,active=activeOrders.filter(o=>o.assignedMotoboyId===m.id&&!['delivered','cancelled'].includes(o.status));return <button key={m.id} onClick={()=>setFocusDriverId(focused?null:m.id)} className={`w-full text-left border rounded-xl p-3 mb-2 ${focused?'border-violet-500 bg-violet-950/15':'border-slate-800 bg-slate-950'}`}><div className="flex justify-between gap-2"><div><b className="text-sm text-white">{m.name}</b><p className="text-xs text-slate-400 mt-1">{driverLabel(m)}</p></div>{qi>=0?<span className={`h-fit rounded-full px-2 py-1 text-[10px] font-bold ${qi===0?'bg-violet-600 text-white':'bg-slate-800 text-slate-300'}`}>{qi===0?'1º da fila · próximo':`${qi+1}º da fila`}</span>:<Bike className="w-4 h-4 text-slate-500"/>}</div><p className="text-xs text-slate-500 mt-2">{active.length} pedido(s) vinculados · retorno {returnEta(m,shift)}</p>{m.status==='returning_to_store'&&<span onClick={e=>{e.stopPropagation();handleCallCounter(m.id,m.name)}} className="inline-block mt-2 text-xs text-violet-300">Chamar no balcão</span>}</button>})}</aside></div>
  </div></div>}
 </div>
};
export default OperationDispatchView;
